Add search block
material-components/material-design-for-wordpress pull request #264
Opened 2021-12-18 14:01 UTC by PatelUtkarsh

## Summary

Fixes #226 

<img width="376" alt="image" src="https://user-images.githubusercontent.com/5015489/146643694-760ddd49-1ad2-4ba2-a775-aa04db57e69c.png">

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/material-components/material-design-for-wordpress/issues) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/material-components/material-design-for-wordpress/blob/main/contributing/engineering.md#tests).
- [ ] My code follows the [Contributing Guidelines](https://github.com/material-components/material-design-for-wordpress/blob/main/contributing.md) (updates are often made to the guidelines, check it out periodically).

2021-12-27 17:40 UTC, emeaguiar requested changes

2021-12-27 17:40 UTC, emeaguiar commented on theme/assets/src/block-editor/blocks/search/edit.js
> + */
```suggestion
```

2021-12-27 17:40 UTC, emeaguiar commented on theme/assets/src/block-editor/blocks/search/edit.js
> +	const search = __( 'Search', 'material-design-google' );
```suggestion
	const search = __( 'Search', 'material-design-google' );

```

2021-12-27 17:40 UTC, emeaguiar commented on theme/assets/src/block-editor/blocks/search/edit.js
> +		<div { ...useBlockProps() }>
This should be a `form` element.

2021-12-27 17:40 UTC, emeaguiar commented on theme/assets/src/block-editor/blocks/search/edit.js
> +					aria-labelledby={ search }
`aria-labelledby` is meant to use an ID, either add a unique ID to the `form` element or switch this to `aria-label`

2021-12-27 17:41 UTC, emeaguiar commented
@PatelUtkarsh Just a couple notes in the block I noticed, otherwise looks good 👍

2022-01-04 08:47 UTC, PatelUtkarsh commented
@emeaguiar Thank you for the feedback, I've updated code and resolved in f189f66.

2022-01-04 15:53 UTC, emeaguiar approved these changes

2022-01-04 15:53 UTC, merged