Add FSE opt-in in customizer
material-components/material-design-for-wordpress pull request #307
Opened 2022-02-14 09:36 UTC by PatelUtkarsh

## Summary

Fixes #255

Todo:
- [ ] Add admin notice to ask users to opt in.
- [ ] Update description.

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/material-components/material-design-for-wordpress/issues) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/material-components/material-design-for-wordpress/blob/main/contributing/engineering.md#tests).
- [ ] My code follows the [Contributing Guidelines](https://github.com/material-components/material-design-for-wordpress/blob/main/contributing.md) (updates are often made to the guidelines, check it out periodically).

2022-06-15 15:02 UTC, PatelUtkarsh commented
Hello @emeaguiar, This is ready for another review. 

For FSE Opt in now it uses setting page from plugin, If plugin is not active then theme registers setting page and enqueue required assets for settings. 

Currently, setting component is shared between plugin and theme both and lives in plugin.

2022-06-21 15:06 UTC, emeaguiar requested changes
@PatelUtkarsh I just have one suggestion about the settings page. Everything else is great!

2022-06-21 17:20 UTC, PatelUtkarsh commented on plugin/assets/src/settings/components/integrations/fse-opt-in.js
> +	const handleAutoUpdateToggle = () => {
Good catch! Updated in [16d33c4](https://github.com/material-components/material-design-for-wordpress/pull/307/commits/16d33c444378117e8b6ef3721631126e803f1dc2)

2022-06-24 14:21 UTC, emeaguiar approved these changes

2022-06-24 14:21 UTC, merged