Release 0.2.0
material-components/material-design-for-wordpress pull request #85
Opened 2021-04-13 17:32 UTC by ravichdev

## Changelog

- Add tooltip option to Button block with icon style.
- Add device specific column options for gallery block.
- Add custom post type support to the "Curated card collection" block.
- Add settings page with options to toggle auto updates and save API key.
- Add option to enable auto updates for Google Icons.
- Add option to enable auto updates for Google Fonts.
- Add option to enable auto updates for Material Design plugin and theme using WordPress core auto updates API.
- Update "Curated card collection" block display in the Block Editor to show a "Preview" button which links to the post.
- Update card header image to use an `img` tag to leverage WordPress core `srcset`.
- Fix a bug in the Block Editor card block where the card header image cannot be removed.

## Props
Thanks to the many contributors who made this release possible through work on development, design, testing, project management, and more:

@ravichdev, @emeaguiar, @csossi, @jauyong, @mattchungxwp, @dawidmlynarz, @rodydavis 

---

- [ ] Write a complete description
- [x] Update changelog
- [x] Add contributors
- [ ] Merge & tag a release

2021-04-13 18:26 UTC, emeaguiar commented
@googlebot I consent.

2021-04-13 18:54 UTC, kasparsd commented
@googlebot I consent.

2021-04-13 18:56 UTC, rodydavis commented
@googlebot I consent.

2021-04-13 19:14 UTC, rodydavis requested changes
Looks good but there are a few files that need a new line at the end. @ravichdev

2021-04-13 19:14 UTC, rodydavis commented on .gitignore
> +theme/composer*
Need a new line at the end of this file

2021-04-13 19:14 UTC, rodydavis commented on phpcs-theme.xml
> +</ruleset>
New line needed at this end of this file

2021-04-14 16:33 UTC, rodydavis requested changes
Missing a blank line as per the style guide

2021-04-14 16:33 UTC, rodydavis commented on plugin/assets/src/block-editor/blocks/image-list/block.json
> +}
Needs a blank line at the end

2021-04-15 08:20 UTC, ravichdev commented
@rodydavis I've added description for the release, please review.

2021-04-15 18:50 UTC, rodydavis commented on plugin/assets/src/block-editor/blocks/image-list/block.json
> +}
@ravichdev  can you push this change?

2021-04-15 18:53 UTC, rodydavis approved these changes
LGTM

2021-04-15 18:53 UTC, merged